name: Deploy on production
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            ${{ runner.os }}-
      - name: Install dependencies
        run: npm ci --cache-min=9999 --no-audit --progress=false
      - name: Format code
        run: npm run prettier:format-all
      - name: Check prettier
        run: npm run prettier:check
      - name: Check linter
        run: npm run lint
      - name: Check unit tests
        run: npm run test:unit
      - name: Build project
        run: npm run build
        env:
          VUE_APP_API_KEY: ${{secrets.VUE_APP_API_KEY}}
          VUE_APP_AUTH_DOMAIN: ${{secrets.VUE_APP_AUTH_DOMAIN}}
          VUE_APP_DATABASE_URL: ${{secrets.VUE_APP_DATABASE_URL}}
          VUE_APP_PROJECT_ID: ${{secrets.VUE_APP_PROJECT_ID}}
          VUE_APP_STORAGE_BUCKET: ${{secrets.VUE_APP_STORAGE_BUCKET}}
          VUE_APP_MESSAGING_SENDER_ID: ${{secrets.VUE_APP_MESSAGING_SENDER_ID}}
          VUE_APP_APP_ID: ${{secrets.VUE_APP_APP_ID}}
          VUE_APP_MEASUREMENT_ID: ${{secrets.VUE_APP_MEASUREMENT_ID}}
          VUE_APP_TITLE: "F.N Artesanato"
          VUE_APP_SHORT_TITLE: "CMVCA"
      - name: Check bundle size
        run: npm run bundlesize
      - name: Upload build
        uses: actions/upload-artifact@master
        with:
          name: build
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup nodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Download build
        uses: actions/download-artifact@master
        with:
          name: build
          path: dist
      - name: Deploy project to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --non-interactive
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
